- name: install depends
  yum: name={{ item }} state=installed
  with_items:
      - python-pip
      - python-devel
      - MySQL-python

- name: 01
  include: sql.yml

- name: 02
  include: create_user.yml
