- name: create keystone database
  mysql_db: name=keystone login_user=root login_password=123456 state="present"

- name: Grant access to the DB for keystone
  mysql_user:
      login_user: root
      login_password: 123456
      name: keystone
      password: 123456
      host: "{{ item }}"
      state: present
      priv: "keystone.*:ALL,GRANT"
  with_items:
      - "localhost"
      - "%"

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
      - openstack-keystone
      - httpd
      - mod_wsgi

- name: Install OpenStackClient
  command: pip install python-openstackclient

- name: modify the /etc/keystone/keystone.conf file
  lineinfile:
      dest: /etc/keystone/keystone.conf
      regexp: '{{ item.key }}'
      line: '{{ item.value }}'
  with_items:
      - {'key': '^#connection =','value': 'connection = mysql+pymysql://keystone:123456@controller/keystone'}
      - {'key': '^#provider = uuid','value':'provider = fernet'}

- name: populate the identity service
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  register: result
  failed_when: result.rc != 0

- name: Initialize Fernet key repositories
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
- name: and
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: Bootstrap the Identity service
  command: keystone-manage bootstrap --bootstrap-password 123456 --bootstrap-admin-url http://controller:35357/v3/ --bootstrap-internal-url http://controller:35357/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

- name: modify the /etc/httpd/conf/httpd.conf file
  lineinfile:
      dest: /etc/httpd/conf/httpd.conf
      regexp: '^#ServerName'
      line: 'ServerName controller'

- name: create link file
  shell: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/

- name: start and enable http service
  service: name=httpd state=started enabled=yes



