- name: install Memcached
  yum: name={{item}} state=installed
  with_items:
      - memcached 
      - python-memcached

- name: modify the /etc/sysconfig/memcached file 
  lineinfile:
      dest: /etc/sysconfig/memcached
      regexp: '^OPTIONS'
      line: 'OPTIONS="-l 127.0.0.1,::1,controller"'

- name: restart memcached
  service: name=memcached state=started enabled=yes

