- name: install centos-release-openstack-newton
  yum: name=centos-release-openstack-ocata state=present

- name: change qemu repo
  template: src=templates/CentOS-QEMU-EV.repo.j2 dest=/etc/yum.repos.d/CentOS-QEMU-EV.repo

- name: start openstack storehouse and install openstack client,openstack-selinux
  yum: name={{item}} state=installed
  with_items:
      - python-openstackclient
      - openstack-selinux


