- name: install chrony
  yum: name=chrony state=installed 

- name: change the /etc/chrony.conf file
  lineinfile: 
      dest: /etc/chrony.conf 
      regexp: '{{ item.regexp }}' 
      line: '{{ item.line }}'
  with_items:
      - { 'regexp': 'server 0.centos.pool.ntp.org iburst', 'line': 'server controller iburst' }
      - { 'regexp': 'server 1.centos.pool.ntp.org iburst', 'line': 'server controller iburst' }
      - { 'regexp': 'server 2.centos.pool.ntp.org iburst', 'line': 'server controller iburst' }
      - { 'regexp': 'server 3.centos.pool.ntp.org iburst', 'line': 'server controller iburst' }

- name: change the /etc/chrony.conf file  
  lineinfile:
      dest: /etc/chrony.conf
      regexp: '^#allow'
      line: 'allow 0.0.0.0/0'

- name: restart NTP
  service: name=chronyd state=restarted enabled=yes
