- name: install network packages for compute node
  yum: name={{item}} state=installed
  with_items:
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset

- name: Edit the /etc/neutron/neutron.conf file
  template: src=templates/neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Edit the /etc/neutron/plugins/ml2/linuxbridge_agent.ini file
  template: src=templates/linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: Edit the /etc/nova/nova.conf file
  template: src=templates/nova.conf.j2 dest=/etc/nova/nova.conf

- name: Restart the Compute service
  service: name=openstack-nova-compute state=restarted

- name: start and enable service
  service: name=neutron-linuxbridge-agent state=started enabled=yes
